name: pubspec_manager
version: 2.0.1
description: Read, write and modify a pubspec.yaml with a type safe API including retention and modifications of comments and out of spec content.
repository: https://github.com/onepub-dev/pubspec_manager
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  meta: ^1.9.1
  path: ^1.8.3
  pub_semver: ^2.1.4
  strings: '>=3.0.0 <5.0.0'
dev_dependencies:
  lint_hard: ^6.0.0
  test: ^1.24.6
