library internal;

import 'dart:collection';
import 'dart:io';

import 'package:meta/meta.dart';
import 'package:path/path.dart';
import 'package:pub_semver/pub_semver.dart' as sm;
import 'package:strings/strings.dart';

import 'document/document.dart';
import 'document/document_writer.dart';
import 'document/line.dart';
import 'document/line_detached.dart';
import 'document/line_section.dart';
import 'document/line_type.dart';
import 'document/multi_line.dart';
import 'document/section.dart';
import 'document/section_single_line.dart';

part 'comments.dart';
part 'dependencies.dart';
part 'dependency.dart';
part 'dependency_alt_hosted.dart';
part 'dependency_alt_hosted_builder.dart';
part 'dependency_builder.dart';
part 'dependency_git.dart';
part 'dependency_git_builder.dart';
part 'dependency_path.dart';
part 'dependency_path_builder.dart';
part 'dependency_pub_hosted.dart';
part 'dependency_pub_hosted_builder.dart';
part 'dependency_sdk.dart';
part 'dependency_sdk_builder.dart';
part 'documentation.dart';
part 'documentation_builder.dart';
part 'environment.dart';
part 'environment_builder.dart';
part 'exceptions.dart';
part 'executable.dart';
part 'executable_builder.dart';
part 'executables.dart';
part 'homepage.dart';
part 'issue_tracker.dart';
part 'issue_tracker_builder.dart';
part 'name.dart';
part 'pub_spec.dart';
part 'publish_to.dart';
part 'repository.dart';
part 'version.dart';
part 'version_builder.dart';
part 'version_constraint.dart';
part 'version_constraint_builder.dart';
